Imports System.Collections.Generic

Public Module LanguageResources
    Private resourcesEs As Dictionary(Of String, String) = Nothing
    Private resourcesEn As Dictionary(Of String, String) = Nothing
    Private resourcesFr As Dictionary(Of String, String) = Nothing
    Private resourcesDe As Dictionary(Of String, String) = Nothing
    Private resourcesIt As Dictionary(Of String, String) = Nothing
    Private resourcesPt As Dictionary(Of String, String) = Nothing
    Private isInitialized As Boolean = False
    
    Private Sub InitializeResources()
        If isInitialized Then Return
        isInitialized = True
        
        resourcesEs = New Dictionary(Of String, String)()
        resourcesEn = New Dictionary(Of String, String)()
        resourcesFr = New Dictionary(Of String, String)()
        resourcesDe = New Dictionary(Of String, String)()
        resourcesIt = New Dictionary(Of String, String)()
        resourcesPt = New Dictionary(Of String, String)()
        ' Recursos en Español
        resourcesEs("Form1.Text") = "Borrar Archivos Duplicados"
        resourcesEs("ToolStripButton1.Text") = "Buscar"
        resourcesEs("btnVistaIconos.Text") = "Vista Iconos"
        resourcesEs("btnVistaDetalles.Text") = "Vista Detalles"
        resourcesEs("btnEliminarSeleccionados.Text") = "Eliminar Archivos Seleccionados"
        resourcesEs("btnIdioma.Text") = "Idioma"
        resourcesEs("lblProgreso.Text") = ""
        resourcesEs("lvDuplicados.Column0") = "Archivo"
        resourcesEs("lvDuplicados.Column1") = "Ruta"
        resourcesEs("lvDuplicados.Column2") = "Tamaño"
        resourcesEs("lvDuplicados.Column3") = "Tipo"
        resourcesEs("MsgNoDuplicados") = "No se encontraron duplicados."
        resourcesEs("MsgIniciandoAnalisis") = "Iniciando análisis..."
        resourcesEs("MsgNoArchivosLista") = "No hay archivos en la lista."
        resourcesEs("MsgNoArchivosSeleccionados") = "No hay archivos seleccionados para eliminar."
        resourcesEs("MsgConfirmarEliminacion") = "¿Está seguro de que desea enviar {0} archivo(s) a la papelera de reciclaje?"
        resourcesEs("MsgTituloConfirmarEliminacion") = "Confirmar eliminación"
        resourcesEs("MsgEliminacionCompletada") = "Eliminación completada.{0}Exitosos: {0}{0}Fallidos: {1}"
        resourcesEs("MsgTituloResultadoEliminacion") = "Resultado de eliminación"
        resourcesEs("MsgIdiomaCambiado") = "El idioma se cambiará completamente al reiniciar la aplicación."
        resourcesEs("MsgTituloIdiomaCambiado") = "Idioma cambiado"
        resourcesEs("MsgGrupo") = "Grupo {0} - {1} archivo(s) duplicado(s)"
        resourcesEs("MsgCargandoMiniaturas") = "Cargando miniaturas: {0} de {1}..."
        resourcesEs("MsgSeEncontraronGrupos") = "Se encontraron {0} grupos de archivos duplicados."
        resourcesEs("MsgEliminandoArchivos") = "Eliminando archivos..."
        resourcesEs("MsgMiniaturasRegeneradas") = "Miniaturas regeneradas."
        resourcesEs("MsgRegenerandoMiniaturas") = "Regenerando miniaturas: {0} de {1}..."
        resourcesEs("MsgRevisandoArchivo") = "Revisando archivo {0} de {1}... Grupos encontrados: {2}"
        resourcesEs("MsgMuchosArchivos") = "Se encontraron {0:N0} archivos. Esto puede tardar mucho tiempo.{1}¿Desea continuar con el análisis completo?"
        resourcesEs("MsgTituloMuchosArchivos") = "Muchos archivos"
        resourcesEs("MsgConfirmacionRequerida") = "Está intentando eliminar {0:N0} archivos.{1}¿Está seguro de continuar?"
        resourcesEs("MsgTituloConfirmacionRequerida") = "Confirmación requerida"
        resourcesEs("MsgTituloInformacion") = "Información"
        resourcesEs("MsgErrorPermisos") = "No se tienen permisos para acceder a: {0}"
        resourcesEs("MsgTituloErrorPermisos") = "Error de permisos"
        resourcesEs("btnSeleccionarTodos.Text") = "Seleccionar Todos"
        resourcesEs("btnDeseleccionarTodos.Text") = "Deseleccionar Todos"
        resourcesEs("btnInvertirSeleccion.Text") = "Invertir Selección"
        resourcesEs("Form2.Text") = "Seleccionar Idioma"
        resourcesEs("Form2.lblTitulo.Text") = "Seleccionar Idioma"
        resourcesEs("Form2.lblSeleccionar.Text") = "Seleccione un idioma:"
        resourcesEs("Form2.btnAceptar.Text") = "Aceptar"
        resourcesEs("Form2.btnCancelar.Text") = "Cancelar"
        resourcesEs("MsgIdiomaCambiado") = "El idioma ha sido cambiado correctamente."

        ' Recursos en Inglés
        resourcesEn("Form1.Text") = "Delete Duplicate Files"
        resourcesEn("ToolStripButton1.Text") = "Search"
        resourcesEn("btnVistaIconos.Text") = "Icons View"
        resourcesEn("btnVistaDetalles.Text") = "Details View"
        resourcesEn("btnEliminarSeleccionados.Text") = "Delete Selected Files"
        resourcesEn("btnIdioma.Text") = "Language"
        resourcesEn("lblProgreso.Text") = ""
        resourcesEn("lvDuplicados.Column0") = "File"
        resourcesEn("lvDuplicados.Column1") = "Path"
        resourcesEn("lvDuplicados.Column2") = "Size"
        resourcesEn("lvDuplicados.Column3") = "Type"
        resourcesEn("MsgNoDuplicados") = "No duplicates found."
        resourcesEn("MsgIniciandoAnalisis") = "Starting analysis..."
        resourcesEn("MsgNoArchivosLista") = "No files in the list."
        resourcesEn("MsgNoArchivosSeleccionados") = "No files selected for deletion."
        resourcesEn("MsgConfirmarEliminacion") = "Are you sure you want to send {0} file(s) to the recycle bin?"
        resourcesEn("MsgTituloConfirmarEliminacion") = "Confirm deletion"
        resourcesEn("MsgEliminacionCompletada") = "Deletion completed.{0}Successful: {0}{0}Failed: {1}"
        resourcesEn("MsgTituloResultadoEliminacion") = "Deletion result"
        resourcesEn("MsgIdiomaCambiado") = "The language will be fully changed when you restart the application."
        resourcesEn("MsgTituloIdiomaCambiado") = "Language changed"
        resourcesEn("MsgGrupo") = "Group {0} - {1} duplicate file(s)"
        resourcesEn("MsgCargandoMiniaturas") = "Loading thumbnails: {0} of {1}..."
        resourcesEn("MsgSeEncontraronGrupos") = "Found {0} groups of duplicate files."
        resourcesEn("MsgEliminandoArchivos") = "Deleting files..."
        resourcesEn("MsgMiniaturasRegeneradas") = "Thumbnails regenerated."
        resourcesEn("MsgRegenerandoMiniaturas") = "Regenerating thumbnails: {0} of {1}..."
        resourcesEn("MsgRevisandoArchivo") = "Reviewing file {0} of {1}... Groups found: {2}"
        resourcesEn("MsgMuchosArchivos") = "Found {0:N0} files. This may take a long time.{1}Do you want to continue with the full analysis?"
        resourcesEn("MsgTituloMuchosArchivos") = "Many files"
        resourcesEn("MsgConfirmacionRequerida") = "You are trying to delete {0:N0} files.{1}Are you sure you want to continue?"
        resourcesEn("MsgTituloConfirmacionRequerida") = "Confirmation required"
        resourcesEn("MsgTituloInformacion") = "Information"
        resourcesEn("MsgErrorPermisos") = "No permission to access: {0}"
        resourcesEn("MsgTituloErrorPermisos") = "Permission error"
        resourcesEn("btnSeleccionarTodos.Text") = "Select All"
        resourcesEn("btnDeseleccionarTodos.Text") = "Deselect All"
        resourcesEn("btnInvertirSeleccion.Text") = "Invert Selection"
        resourcesEn("Form2.Text") = "Select Language"
        resourcesEn("Form2.lblTitulo.Text") = "Select Language"
        resourcesEn("Form2.lblSeleccionar.Text") = "Select a language:"
        resourcesEn("Form2.btnAceptar.Text") = "Accept"
        resourcesEn("Form2.btnCancelar.Text") = "Cancel"
        resourcesEn("MsgIdiomaCambiado") = "The language has been changed successfully."

        ' Recursos en Francés
        resourcesFr("Form1.Text") = "Supprimer les fichiers en double"
        resourcesFr("ToolStripButton1.Text") = "Rechercher"
        resourcesFr("btnVistaIconos.Text") = "Vue Icônes"
        resourcesFr("btnVistaDetalles.Text") = "Vue Détails"
        resourcesFr("btnEliminarSeleccionados.Text") = "Supprimer les fichiers sélectionnés"
        resourcesFr("btnIdioma.Text") = "Langue"
        resourcesFr("lblProgreso.Text") = ""
        resourcesFr("lvDuplicados.Column0") = "Fichier"
        resourcesFr("lvDuplicados.Column1") = "Chemin"
        resourcesFr("lvDuplicados.Column2") = "Taille"
        resourcesFr("lvDuplicados.Column3") = "Type"
        resourcesFr("MsgNoDuplicados") = "Aucun doublon trouvé."
        resourcesFr("MsgIniciandoAnalisis") = "Démarrage de l'analyse..."
        resourcesFr("MsgNoArchivosLista") = "Aucun fichier dans la liste."
        resourcesFr("MsgNoArchivosSeleccionados") = "Aucun fichier sélectionné pour la suppression."
        resourcesFr("MsgConfirmarEliminacion") = "Êtes-vous sûr de vouloir envoyer {0} fichier(s) à la corbeille ?"
        resourcesFr("MsgTituloConfirmarEliminacion") = "Confirmer la suppression"
        resourcesFr("MsgEliminacionCompletada") = "Suppression terminée.{0}Réussis : {0}{0}Échoués : {1}"
        resourcesFr("MsgTituloResultadoEliminacion") = "Résultat de la suppression"
        resourcesFr("MsgIdiomaCambiado") = "La langue sera complètement changée au redémarrage de l'application."
        resourcesFr("MsgTituloIdiomaCambiado") = "Langue changée"
        resourcesFr("MsgGrupo") = "Groupe {0} - {1} fichier(s) en double"
        resourcesFr("MsgCargandoMiniaturas") = "Chargement des miniatures : {0} sur {1}..."
        resourcesFr("MsgSeEncontraronGrupos") = "{0} groupes de fichiers en double trouvés."
        resourcesFr("MsgEliminandoArchivos") = "Suppression des fichiers..."
        resourcesFr("MsgMiniaturasRegeneradas") = "Miniatures régénérées."
        resourcesFr("MsgRegenerandoMiniaturas") = "Régénération des miniatures : {0} sur {1}..."
        resourcesFr("MsgRevisandoArchivo") = "Examen du fichier {0} sur {1}... Groupes trouvés : {2}"
        resourcesFr("MsgMuchosArchivos") = "{0:N0} fichiers trouvés. Cela peut prendre beaucoup de temps.{1}Voulez-vous continuer avec l'analyse complète ?"
        resourcesFr("MsgTituloMuchosArchivos") = "Beaucoup de fichiers"
        resourcesFr("MsgConfirmacionRequerida") = "Vous essayez de supprimer {0:N0} fichiers.{1}Êtes-vous sûr de vouloir continuer ?"
        resourcesFr("MsgTituloConfirmacionRequerida") = "Confirmation requise"
        resourcesFr("MsgTituloInformacion") = "Information"
        resourcesFr("MsgErrorPermisos") = "Aucune permission d'accès à : {0}"
        resourcesFr("MsgTituloErrorPermisos") = "Erreur de permission"
        resourcesFr("Form2.Text") = "Sélectionner la langue"
        resourcesFr("Form2.lblTitulo.Text") = "Sélectionner la langue"
        resourcesFr("Form2.lblSeleccionar.Text") = "Sélectionnez une langue :"
        resourcesFr("Form2.btnAceptar.Text") = "Accepter"
        resourcesFr("Form2.btnCancelar.Text") = "Annuler"
        resourcesFr("MsgIdiomaCambiado") = "La langue a été modifiée avec succès."

        ' Recursos en Alemán
        resourcesDe("Form1.Text") = "Doppelte Dateien löschen"
        resourcesDe("ToolStripButton1.Text") = "Suchen"
        resourcesDe("btnVistaIconos.Text") = "Symbolansicht"
        resourcesDe("btnVistaDetalles.Text") = "Detailansicht"
        resourcesDe("btnEliminarSeleccionados.Text") = "Ausgewählte Dateien löschen"
        resourcesDe("btnIdioma.Text") = "Sprache"
        resourcesDe("lblProgreso.Text") = ""
        resourcesDe("lvDuplicados.Column0") = "Datei"
        resourcesDe("lvDuplicados.Column1") = "Pfad"
        resourcesDe("lvDuplicados.Column2") = "Größe"
        resourcesDe("lvDuplicados.Column3") = "Typ"
        resourcesDe("MsgNoDuplicados") = "Keine Duplikate gefunden."
        resourcesDe("MsgIniciandoAnalisis") = "Analyse wird gestartet..."
        resourcesDe("MsgNoArchivosLista") = "Keine Dateien in der Liste."
        resourcesDe("MsgNoArchivosSeleccionados") = "Keine Dateien zum Löschen ausgewählt."
        resourcesDe("MsgConfirmarEliminacion") = "Möchten Sie wirklich {0} Datei(en) in den Papierkorb verschieben?"
        resourcesDe("MsgTituloConfirmarEliminacion") = "Löschen bestätigen"
        resourcesDe("MsgEliminacionCompletada") = "Löschen abgeschlossen.{0}Erfolgreich: {0}{0}Fehlgeschlagen: {1}"
        resourcesDe("MsgTituloResultadoEliminacion") = "Löschergebnis"
        resourcesDe("MsgIdiomaCambiado") = "Die Sprache wird vollständig geändert, wenn Sie die Anwendung neu starten."
        resourcesDe("MsgTituloIdiomaCambiado") = "Sprache geändert"
        resourcesDe("MsgGrupo") = "Gruppe {0} - {1} doppelte Datei(en)"
        resourcesDe("MsgCargandoMiniaturas") = "Miniaturansichten laden: {0} von {1}..."
        resourcesDe("MsgSeEncontraronGrupos") = "{0} Gruppen doppelter Dateien gefunden."
        resourcesDe("MsgEliminandoArchivos") = "Dateien werden gelöscht..."
        resourcesDe("MsgMiniaturasRegeneradas") = "Miniaturansichten regeneriert."
        resourcesDe("MsgRegenerandoMiniaturas") = "Miniaturansichten regenerieren: {0} von {1}..."
        resourcesDe("MsgRevisandoArchivo") = "Datei {0} von {1} wird überprüft... Gefundene Gruppen: {2}"
        resourcesDe("MsgMuchosArchivos") = "{0:N0} Dateien gefunden. Dies kann sehr lange dauern.{1}Möchten Sie mit der vollständigen Analyse fortfahren?"
        resourcesDe("MsgTituloMuchosArchivos") = "Viele Dateien"
        resourcesDe("MsgConfirmacionRequerida") = "Sie versuchen, {0:N0} Dateien zu löschen.{1}Sind Sie sicher, dass Sie fortfahren möchten?"
        resourcesDe("MsgTituloConfirmacionRequerida") = "Bestätigung erforderlich"
        resourcesDe("MsgTituloInformacion") = "Information"
        resourcesDe("MsgErrorPermisos") = "Keine Berechtigung für den Zugriff auf: {0}"
        resourcesDe("MsgTituloErrorPermisos") = "Berechtigungsfehler"
        resourcesDe("btnSeleccionarTodos.Text") = "Alle auswählen"
        resourcesDe("btnDeseleccionarTodos.Text") = "Alle abwählen"
        resourcesDe("btnInvertirSeleccion.Text") = "Auswahl umkehren"
        resourcesDe("Form2.Text") = "Sprache auswählen"
        resourcesDe("Form2.lblTitulo.Text") = "Sprache auswählen"
        resourcesDe("Form2.lblSeleccionar.Text") = "Wählen Sie eine Sprache:"
        resourcesDe("Form2.btnAceptar.Text") = "Akzeptieren"
        resourcesDe("Form2.btnCancelar.Text") = "Abbrechen"
        resourcesDe("MsgIdiomaCambiado") = "Die Sprache wurde erfolgreich geändert."

        ' Recursos en Italiano
        resourcesIt("Form1.Text") = "Elimina file duplicati"
        resourcesIt("ToolStripButton1.Text") = "Cerca"
        resourcesIt("btnVistaIconos.Text") = "Vista Icone"
        resourcesIt("btnVistaDetalles.Text") = "Vista Dettagli"
        resourcesIt("btnEliminarSeleccionados.Text") = "Elimina file selezionati"
        resourcesIt("btnIdioma.Text") = "Lingua"
        resourcesIt("lblProgreso.Text") = ""
        resourcesIt("lvDuplicados.Column0") = "File"
        resourcesIt("lvDuplicados.Column1") = "Percorso"
        resourcesIt("lvDuplicados.Column2") = "Dimensione"
        resourcesIt("lvDuplicados.Column3") = "Tipo"
        resourcesIt("MsgNoDuplicados") = "Nessun duplicato trovato."
        resourcesIt("MsgIniciandoAnalisis") = "Avvio analisi..."
        resourcesIt("MsgNoArchivosLista") = "Nessun file nell'elenco."
        resourcesIt("MsgNoArchivosSeleccionados") = "Nessun file selezionato per l'eliminazione."
        resourcesIt("MsgConfirmarEliminacion") = "Sei sicuro di voler inviare {0} file al cestino?"
        resourcesIt("MsgTituloConfirmarEliminacion") = "Conferma eliminazione"
        resourcesIt("MsgEliminacionCompletada") = "Eliminazione completata.{0}Riusciti: {0}{0}Falliti: {1}"
        resourcesIt("MsgTituloResultadoEliminacion") = "Risultato eliminazione"
        resourcesIt("MsgIdiomaCambiado") = "La lingua verrà completamente cambiata al riavvio dell'applicazione."
        resourcesIt("MsgTituloIdiomaCambiado") = "Lingua cambiata"
        resourcesIt("MsgGrupo") = "Gruppo {0} - {1} file duplicato/i"
        resourcesIt("MsgCargandoMiniaturas") = "Caricamento miniature: {0} di {1}..."
        resourcesIt("MsgSeEncontraronGrupos") = "Trovati {0} gruppi di file duplicati."
        resourcesIt("MsgEliminandoArchivos") = "Eliminazione file..."
        resourcesIt("MsgMiniaturasRegeneradas") = "Miniature rigenerate."
        resourcesIt("MsgRegenerandoMiniaturas") = "Rigenerazione miniature: {0} di {1}..."
        resourcesIt("MsgRevisandoArchivo") = "Revisione file {0} di {1}... Gruppi trovati: {2}"
        resourcesIt("MsgMuchosArchivos") = "Trovati {0:N0} file. Questo potrebbe richiedere molto tempo.{1}Vuoi continuare con l'analisi completa?"
        resourcesIt("MsgTituloMuchosArchivos") = "Molti file"
        resourcesIt("MsgConfirmacionRequerida") = "Stai tentando di eliminare {0:N0} file.{1}Sei sicuro di voler continuare?"
        resourcesIt("MsgTituloConfirmacionRequerida") = "Conferma richiesta"
        resourcesIt("MsgTituloInformacion") = "Informazione"
        resourcesIt("MsgErrorPermisos") = "Nessun permesso per accedere a: {0}"
        resourcesIt("MsgTituloErrorPermisos") = "Errore permessi"
        resourcesIt("btnSeleccionarTodos.Text") = "Seleziona tutto"
        resourcesIt("btnDeseleccionarTodos.Text") = "Deseleziona tutto"
        resourcesIt("btnInvertirSeleccion.Text") = "Inverti selezione"
        resourcesIt("Form2.Text") = "Seleziona lingua"
        resourcesIt("Form2.lblTitulo.Text") = "Seleziona lingua"
        resourcesIt("Form2.lblSeleccionar.Text") = "Seleziona una lingua:"
        resourcesIt("Form2.btnAceptar.Text") = "Accetta"
        resourcesIt("Form2.btnCancelar.Text") = "Annulla"
        resourcesIt("MsgIdiomaCambiado") = "La lingua è stata modificata con successo."

        ' Recursos en Portugués
        resourcesPt("Form1.Text") = "Excluir arquivos duplicados"
        resourcesPt("ToolStripButton1.Text") = "Buscar"
        resourcesPt("btnVistaIconos.Text") = "Vista Ícones"
        resourcesPt("btnVistaDetalles.Text") = "Vista Detalhes"
        resourcesPt("btnEliminarSeleccionados.Text") = "Excluir arquivos selecionados"
        resourcesPt("btnIdioma.Text") = "Idioma"
        resourcesPt("lblProgreso.Text") = ""
        resourcesPt("lvDuplicados.Column0") = "Arquivo"
        resourcesPt("lvDuplicados.Column1") = "Caminho"
        resourcesPt("lvDuplicados.Column2") = "Tamanho"
        resourcesPt("lvDuplicados.Column3") = "Tipo"
        resourcesPt("MsgNoDuplicados") = "Nenhum duplicado encontrado."
        resourcesPt("MsgIniciandoAnalisis") = "Iniciando análise..."
        resourcesPt("MsgNoArchivosLista") = "Nenhum arquivo na lista."
        resourcesPt("MsgNoArchivosSeleccionados") = "Nenhum arquivo selecionado para exclusão."
        resourcesPt("MsgConfirmarEliminacion") = "Tem certeza de que deseja enviar {0} arquivo(s) para a lixeira?"
        resourcesPt("MsgTituloConfirmarEliminacion") = "Confirmar exclusão"
        resourcesPt("MsgEliminacionCompletada") = "Exclusão concluída.{0}Bem-sucedidos: {0}{0}Falhados: {1}"
        resourcesPt("MsgTituloResultadoEliminacion") = "Resultado da exclusão"
        resourcesPt("MsgIdiomaCambiado") = "O idioma será completamente alterado ao reiniciar o aplicativo."
        resourcesPt("MsgTituloIdiomaCambiado") = "Idioma alterado"
        resourcesPt("MsgGrupo") = "Grupo {0} - {1} arquivo(s) duplicado(s)"
        resourcesPt("MsgCargandoMiniaturas") = "Carregando miniaturas: {0} de {1}..."
        resourcesPt("MsgSeEncontraronGrupos") = "Encontrados {0} grupos de arquivos duplicados."
        resourcesPt("MsgEliminandoArchivos") = "Excluindo arquivos..."
        resourcesPt("MsgMiniaturasRegeneradas") = "Miniaturas regeneradas."
        resourcesPt("MsgRegenerandoMiniaturas") = "Regenerando miniaturas: {0} de {1}..."
        resourcesPt("MsgRevisandoArchivo") = "Revisando arquivo {0} de {1}... Grupos encontrados: {2}"
        resourcesPt("MsgMuchosArchivos") = "Encontrados {0:N0} arquivos. Isso pode levar muito tempo.{1}Deseja continuar com a análise completa?"
        resourcesPt("MsgTituloMuchosArchivos") = "Muitos arquivos"
        resourcesPt("MsgConfirmacionRequerida") = "Você está tentando excluir {0:N0} arquivos.{1}Tem certeza de que deseja continuar?"
        resourcesPt("MsgTituloConfirmacionRequerida") = "Confirmação necessária"
        resourcesPt("MsgTituloInformacion") = "Informação"
        resourcesPt("MsgErrorPermisos") = "Sem permissão para acessar: {0}"
        resourcesPt("MsgTituloErrorPermisos") = "Erro de permissão"
        resourcesPt("btnSeleccionarTodos.Text") = "Selecionar todos"
        resourcesPt("btnDeseleccionarTodos.Text") = "Desselecionar todos"
        resourcesPt("btnInvertirSeleccion.Text") = "Inverter seleção"
        resourcesPt("Form2.Text") = "Selecionar idioma"
        resourcesPt("Form2.lblTitulo.Text") = "Selecionar idioma"
        resourcesPt("Form2.lblSeleccionar.Text") = "Selecione um idioma:"
        resourcesPt("Form2.btnAceptar.Text") = "Aceitar"
        resourcesPt("Form2.btnCancelar.Text") = "Cancelar"
        resourcesPt("MsgIdiomaCambiado") = "O idioma foi alterado com sucesso."
    End Sub

    Public Function GetResource(languageCode As String, key As String) As String
        InitializeResources()
        
        Dim resources As Dictionary(Of String, String) = Nothing
        
        Select Case languageCode.ToLower()
            Case "es-es"
                resources = resourcesEs
            Case "en-us"
                resources = resourcesEn
            Case "fr-fr"
                resources = resourcesFr
            Case "de-de"
                resources = resourcesDe
            Case "it-it"
                resources = resourcesIt
            Case "pt-pt"
                resources = resourcesPt
            Case Else
                resources = resourcesEn ' Por defecto inglés
        End Select
        
        If resources IsNot Nothing AndAlso resources.ContainsKey(key) Then
            Return resources(key)
        End If
        
        Return key ' Retornar la clave si no se encuentra
    End Function
End Module

